excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - Pods/
line_length: 1000

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - force_cast
  - todo
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - file_length
  - unused_optional_binding
  - implicit_getter
  - shorthand_operator
  - nesting
  - switch_case_alignment
  - orphaned_doc_comment
  - type_name
  - large_tuple
  - trailing_comma
  - type_body_length

analyzer_rules:
- unused_import

function_body_length:
    warning: 50
    error: 150